#+TITLE: Climate change:Half world's biggest airlines don't offer carbon offsetting
#+AUTHOR: Bei Fang
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css"/>

Less than half of the world's major airlines are giving passengers theopportunity to offset the carbon dioxide produced from their flights, BBC research found.

When airlines do offer such a scheme, generally fewer than 1% of flyers are choosing to spend more.

Carbon offsetting enables passengers to balance out their carbon footprint by paying towards environmental projects.

Aviation accounts for 2% of global human-induced greenhouse gas emissions.

Prices vary but a return flight from London to Malaga, Spain, would cost around $4 to offset.

The BBC contacted the world's biggest airlines in terms of numbers of flights and numbers of passengers.

Out of the 28 approached, less than half offered a carbon offset scheme and the majority declined to provide data on the number of passengers offsetting their flights during a one year period-often saying their figures were too low to report.

Michael Gill, a director from the international aviation trade body lata, said:"We strongly recommend all passengers to use high-quality projects to offset their own CO2 emissions as an individual contribution to addressing climate change."

What is carbon offsetting?

Carbon offsetting allows passengers to pay extra to help compensate for the carbon emissions produced from their flight.

The money is then invested in environmental projects - like planting trees or installing solar panels - which reduce the carbon dioxide in the air by the same amount.

Passengers can pay the additional charge when they buy their ticket from participating airlines, but independent offsetting companies also exit.

The price varies between airlines, but a return flight from London and Cape Town, South Africa would cost roughly $20 to offset, according to ClimateCare.

The CO2 emissions per passenger from that flight is roughly the same as those produced from heating the average home for a year.

Some activities have criticized carbon offsetting as an excuse to continue polluting, arguing that it does little to change behaviour. Advocates defend offsetting just as vociferously.

